#!/bin/bash -x


for filename in foo; do #Replace foo with file path
    result=
    if [ -f $filename ]; then
        result="$filename is a regular file"
    else
        if [ -d $filename ]; then
            result="$filename is a directory"
        fi
    fi
    if [ -w $filename ]; then
        result="$result and it is writable"
    else
        result="$result and it is not writable"
    fi
    echo "$result"
done
