#!/bin/bash
#if command


if [ -f .bash_profile ]; then
    echo "You have a .bash_profile. Things are fine."
else
    echo "Yikes! You have no .bash_profile, go create one"
fi
 
if [ -d foo ]; then #replace foo with file path
    echo "It's a directory."
else
    echo "Yikes! It is not a directory"
fi  

if [ $(id -u)="0" ]; then
    echo "Super User, Genie is ready to grant you wishes."
else
    echo "You aren't a Super User, Genie can't care any less."
fi   

exit 0
