#!/bin/bash -x

# Script License: GPL
# Dependensies: ffmpeg (You need ffmpeg installed in your system)
# Usage: "Takes single/multiple file paths as input and converts them to mp3"
# Example: "./vid_mp3.sh Downloads/Amsterdam\ Imagine\ Dragons.flv Downloads/BrownRang.mp4" converts 'Downloads/Amsterdam Imagine Dragons.flv' and 'Downloads/BrownRang.mp4' to 'Downloads/Amsterdam Imagine Dragons.flv.mp3' and 'Downloads/BrownRang.mp4.mp3'
# script by pahnin

if [ $# -gt 0 ]; then
    while test $# -gt 0
    do
        Filo=${1//\ /\\\ };
        echo "
Converting $Filo
Command: ffmpeg -i $Filo -vn $Filo.mp3"
        eval "ffmpeg -i $Filo -vn $Filo.mp3 "
        shift
    done
else
    echo "
Which video file to convert?
Script usage ./vid_mp3.sh <video filepath> ...
";
fi
